"""
French-to-English grammatical abbreviations for Heritage Platform.
Extracted from docs/plans/active/skt/HERITAGE_ABBR.md
"""

GRAMMATICAL_ABBREVIATIONS = {
    "S.": "substantive / noun",
    "SOC.": "society",
    "V.": "verb",
    "VOC.": "vocative",
    "ZOO.": "zoology",
    "a.": "adjective",
    "abl.": "ablative",
    "abs.": "absolutive",
    "abstr.": "abstract",
    "ac.": "active",
    "acc.": "accusative",
    "act.": "action",
    "adr.": "term of address",
    "adv.": "adverb",
    "agt.": "agent",
    "all.": "German",
    "ang.": "English",
    "ant.": "before the common era",
    "aor.": "aorist",
    "approx.": "approximately",
    "arch.": "architecture",
    "astr.": "astronomy",
    "av.": "with",
    "bd.": "Buddhism",
    "bio.": "biology",
    "bén.": "benedictive",
    "c.-à-d.": "that is to say / i.e.",
    "cf.": "compare / see",
    "cl.": "clitic",
    "comp.": "compound",
    "compar.": "comparative",
    "cond.": "conditional",
    "conj.": "conjunction",
    "cons.": "consonant",
    "contr.": "contraction",
    "corr.": "corresponding",
    "corrél.": "correlative",
    "dat.": "dative",
    "du.": "dual",
    "dém.": "demonstrative",
    "dés.": "desiderative",
    "ex.": "example",
    "excl.": "exclamatory",
    "ext.": "extension",
    "f.": "feminine",
    "fb.": "weak",
    "fig.": "figurative",
    "fr.": "French",
    "fut.": "future",
    "g.": "genitive",
    "gr.": "Greek",
    "gram.": "grammar",
    "gém.": "geminated",
    "gén.": "general",
    "géo.": "geography",
    "hi.": "Hindi",
    "hist.": "history",
    "hom.": "homonym",
    "i.": "instrumental",
    "ic.": "in composition",
    "id.": "the same",
    "ifc.": "at the end of a compound",
    "iic.": "at the beginning of a compound",
    "iiv.": "at the beginning of a verb",
    "imp.": "imperative",
    "impers.": "impersonal",
    "impft.": "imperfect",
    "ind.": "indeclinable",
    "inf.": "infinitive",
    "inj.": "injunctive",
    "instr.": "instrument",
    "intens.": "intensive",
    "interj.": "interjection",
    "interr.": "interrogative",
    "jn.": "Jainism",
    "lat.": "Latin",
    "lex.": "lexicography",
    "lit.": "literature",
    "litt.": "literally",
    "loc.": "locative",
    "m.": "masculine",
    "math.": "mathematics",
    "mo.": "middle",
    "mod.": "modern",
    "mus.": "music",
    "myth.": "mythology",
    "méd.": "medicine",
    "n.": "neuter",
    "nom.": "nominative",
    "not.": "notably",
    "nota.": "notation",
    "num.": "numeral",
    "nég.": "negation",
    "obj.": "object",
    "obl.": "oblique",
    "opp.": "opposite to",
    "ord.": "ordinal",
    "part.": "particle",
    "patr.": "patronymic",
    "pers.": "person",
    "pf.": "prefix",
    "pfp.": "future passive participle",
    "pft.": "perfect",
    "pfut.": "future participle",
    "phil.": "philosophy",
    "phon.": "phonetics",
    "pl.": "plural",
    "poss.": "possessive",
    "pp.": "past passive participle",
    "ppa.": "past active participle",
    "ppft.": "perfect participle",
    "ppr.": "present participle",
    "pr.": "present",
    "priv.": "privative",
    "prk.": "Prakrit",
    "pron.": "pronoun",
    "prép.": "preposition",
    "ps.": "passive",
    "pt.": "Portuguese",
    "péj.": "pejorative",
    "péri.": "periphrastic",
    "qqc.": "something",
    "qqf.": "sometimes",
    "qqn.": "someone",
    "red.": "reduplication",
    "resp.": "respectively",
    "rhét.": "rhetoric",
    "ru.": "Russian",
    "sf.": "suffix",
    "sg.": "singular",
    "subj.": "subjunctive",
    "super.": "superlative",
    "suppl.": "suppletive",
    "symb.": "symbolic",
    "syn.": "synonym",
    "tantr.": "tantric",
    "th.": "theme",
    "var.": "variant",
    "vn.": "nominal verb",
    "vr.": "vṛddhi",
    "véd.": "Vedic",
    "épith.": "epithet",
    "пр.": "proper noun",
    "са.": "causative",
}
