# from langnet.foster.latin import FOSTER_LATIN_CASES, FOSTER_LATIN_TENSES, FOSTER_LATIN_GENDERS, FOSTER_LATIN_NUMBERS, FOSTER_LATIN_MISCELLANEOUS
# from langnet.foster.greek import FOSTER_GREEK_CASES, FOSTER_GREEK_TENSES, FOSTER_GREEK_GENDERS, FOSTER_GREEK_NUMBERS, FOSTER_GREEK_MISCELLANEOUS
# from langnet.foster.sanskrit import FOSTER_SANSKRIT_CASES, FOSTER_SANSKRIT_GENDERS, FOSTER_SANSKRIT_NUMBERS
