import assert from 'node:assert/strict';
import {
	encounterBriefingCanGenerate,
	encounterBriefingCompactText,
	encounterBriefingIsGenerated,
	encounterBriefingProvenanceLabel,
	encounterBriefingOutput,
	encounterBriefingStatusLabel,
	type EncounterBriefingFlow
} from './encounter-briefing';

const draftFlow: EncounterBriefingFlow = {
	schema_version: 'langnet.encounter_briefing.flow.v1',
	generation: { status: 'cache_miss' },
	draft_output: {
		schema_version: 'langnet.encounter_briefing.summary.v1',
		short: 'arma: arms or weapons.',
		forms: ['arma'],
		meanings: [],
		grammar_functions: [],
		word_decomposition: [],
		reader_usages: [],
		phrase_pairs: [],
		dictionary_sources: ['whitaker'],
		caveats: []
	}
};

assert.equal(encounterBriefingOutput(draftFlow)?.short, 'arma: arms or weapons.');
assert.equal(encounterBriefingIsGenerated(draftFlow), false);
assert.equal(encounterBriefingStatusLabel(draftFlow), 'Draft');
assert.equal(encounterBriefingProvenanceLabel(draftFlow), 'Draft');
assert.equal(encounterBriefingCanGenerate(draftFlow), false);

const sourceBackedDraftFlow: EncounterBriefingFlow = {
	...draftFlow,
	draft_output: {
		...draftFlow.draft_output!,
		meanings: [
			{
				summary: 'arms or weapons',
				source_glosses: ['arms or weapons'],
				source_gloss_language: 'en',
				translation_status: 'english-or-unknown',
				sources: ['whitaker'],
				translation_sources: [],
				source_refs: ['whitaker:arma']
			}
		]
	}
};

assert.equal(encounterBriefingCanGenerate(sourceBackedDraftFlow), true);

const cachedFlow: EncounterBriefingFlow = {
	...draftFlow,
	generation: {
		status: 'cache_hit',
		cached_status: 'accepted',
		model: 'openai:qwen/qwen3.7-max'
	},
	final_output: {
		...draftFlow.draft_output!,
		short: 'arma can mean arms, weapons, or martial equipment.'
	}
};

assert.equal(
	encounterBriefingOutput(cachedFlow)?.short,
	'arma can mean arms, weapons, or martial equipment.'
);
assert.equal(encounterBriefingIsGenerated(cachedFlow), true);
assert.equal(encounterBriefingStatusLabel(cachedFlow), 'Generated');
assert.equal(encounterBriefingProvenanceLabel(cachedFlow), 'Generated by qwen/qwen3.7-max');
assert.equal(encounterBriefingCanGenerate(cachedFlow), false);

const rejectedCachedFlow: EncounterBriefingFlow = {
	...draftFlow,
	generation: { status: 'cache_hit', cached_status: 'rejected' },
	final_output: draftFlow.draft_output
};

assert.equal(encounterBriefingIsGenerated(rejectedCachedFlow), false);
assert.equal(encounterBriefingStatusLabel(rejectedCachedFlow), 'Draft');

const acceptedFlow: EncounterBriefingFlow = {
	...draftFlow,
	generation: { status: 'accepted', model: 'openai:qwen/qwen3.7-max' },
	final_output: cachedFlow.final_output
};

assert.equal(encounterBriefingIsGenerated(acceptedFlow), true);
assert.equal(encounterBriefingStatusLabel(acceptedFlow), 'Generated');
assert.equal(encounterBriefingProvenanceLabel(acceptedFlow), 'Generated by qwen/qwen3.7-max');

assert.equal(encounterBriefingCompactText('short gloss', 30), 'short gloss');
assert.equal(
	encounterBriefingCompactText(
		'reward of good tidings, given to the messenger, εὐαγγέλιον δέ μοι ἔστω Od. 14.152;',
		64
	),
	'reward of good tidings, given to the messenger, εὐαγγέλιον δέ...'
);

console.log('encounter briefing helpers ok');
